---
# tasks file for roles/DOCKER
- name: Pull DOCKER IMAGE
  docker_image:
     name: httpd
     tag: latest
     source: pull
  register: z
- name: Pull Status
  debug:
    var: z

- name: Creating a Persistent Volume Dir
  file:
    path: "/root/pv"
    state: directory

- name: Copying the HTML code in the Directory
  copy:
    src: "./docker/web/index.html"
    dest: "/root/pv"

- name: Launch httpd container
  when: z.failed == false
  docker_container:
    name: apache-server
    image: httpd
    state: started
    exposed_ports:
      - "80"
    ports:
      - "8888:8080"
    volumes:
      - /root/pv:/usr/local/apache2/htdocs
